# The amount of Minecraft ticks between each Pylon tick
tick-delay: 1

# The number of errors a ticking block can throw before it is disabled
allowed-block-errors: 5

# The interval, in ticks, between WAILA checks
waila-interval: 1

research:
  enabled: true
  # The interval, in ticks, between when Pylon checks for unresearched items in inventories
  interval: 1

# How many characters a line can be before it is split into a new line when translating
translation-wrap-limit: 64