# The amount of Minecraft ticks between each Pylon tick
tick-delay: 1

# The number of errors a ticking block can throw before it is disabled
allowed-block-errors: 5

# The interval, in ticks, between WALIA checks
walia-interval: 1

# The interval, in ticks, between when Pylon checks for unresearched items in inventories
# Set to 0 to disable researching
research-interval: 10