# The amount of Minecraft ticks between each Pylon tick
tick-rate: 1

# The number of errors a ticking block can throw before it is disabled
allowed-block-errors: 5

# The interval, in ticks, between WAILA checks
waila-interval-ticks: 1

# The interval between fluid network ticks
fluid-interval-ticks: 1

block-data-autosave-interval-seconds: 3

entity-data-autosave-interval-seconds: 3

research:
  enabled: true
  # The interval, in ticks, between when Pylon checks for unresearched items in inventories
  interval: 20

# How many characters a line can be before it is split into a new line when translating
translation-wrap-limit: 64