name: Live Testing

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

jobs:
  live-testing:
    name: Live Testing
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup server
        run: |
          echo 'eula=true' > eula.txt
          mkdir plugins

      - name: Download Pylon
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.artifact-name }}
          path: plugins/

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.2.2

      - name: Run server
        run: ./gradlew runServer
