name: Publish to Central Repository

on:
  push:
    tags: ['*']

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Publish snapshot
      run: ./gradlew publishToCentralPortal -Pversion=${GITHUB_REF/refs\/tags\//}
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SIGNING_KEY: ${{ secrets.PGP_KEY }}
        SIGNING_PASSWORD: ${{ secrets.PGP_PASSWORD }}